name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜运行

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .tsbuildinfo
          key: ${{ runner.os }}-node-${{ hashFiles('**/bun.lockb') }}

      - name: Install
        run: bun install

      - name: Update
        run: bunx npm-check-updates -u && bun install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update dependencies
          title: Update dependencies
          body: This PR updates dependencies to their latest versions
          branch: 'update-dependencies/${{ github.head_ref }}'
